spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minicampus?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: a1234
  
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
logging:
  level:
    root: info
    
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  upload-dir: C:/App/Spring_Projects/fastlms3/uploads

